// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: agones/allocation.proto
// Original file comments:
// Copyright 2020 Google LLC All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_agones_2fallocation_2eproto__INCLUDED
#define GRPC_agones_2fallocation_2eproto__INCLUDED

#include "agones/allocation.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace allocation {

class AllocationService final {
 public:
  static constexpr char const* service_full_name() {
    return "allocation.AllocationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Allocate(::grpc::ClientContext* context, const ::allocation::AllocationRequest& request, ::allocation::AllocationResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::allocation::AllocationResponse>> AsyncAllocate(::grpc::ClientContext* context, const ::allocation::AllocationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::allocation::AllocationResponse>>(AsyncAllocateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::allocation::AllocationResponse>> PrepareAsyncAllocate(::grpc::ClientContext* context, const ::allocation::AllocationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::allocation::AllocationResponse>>(PrepareAsyncAllocateRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Allocate(::grpc::ClientContext* context, const ::allocation::AllocationRequest* request, ::allocation::AllocationResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Allocate(::grpc::ClientContext* context, const ::allocation::AllocationRequest* request, ::allocation::AllocationResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Allocate(::grpc::ClientContext* context, const ::allocation::AllocationRequest* request, ::allocation::AllocationResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::allocation::AllocationResponse>* AsyncAllocateRaw(::grpc::ClientContext* context, const ::allocation::AllocationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::allocation::AllocationResponse>* PrepareAsyncAllocateRaw(::grpc::ClientContext* context, const ::allocation::AllocationRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Allocate(::grpc::ClientContext* context, const ::allocation::AllocationRequest& request, ::allocation::AllocationResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::allocation::AllocationResponse>> AsyncAllocate(::grpc::ClientContext* context, const ::allocation::AllocationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::allocation::AllocationResponse>>(AsyncAllocateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::allocation::AllocationResponse>> PrepareAsyncAllocate(::grpc::ClientContext* context, const ::allocation::AllocationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::allocation::AllocationResponse>>(PrepareAsyncAllocateRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Allocate(::grpc::ClientContext* context, const ::allocation::AllocationRequest* request, ::allocation::AllocationResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Allocate(::grpc::ClientContext* context, const ::allocation::AllocationRequest* request, ::allocation::AllocationResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Allocate(::grpc::ClientContext* context, const ::allocation::AllocationRequest* request, ::allocation::AllocationResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::allocation::AllocationResponse>* AsyncAllocateRaw(::grpc::ClientContext* context, const ::allocation::AllocationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::allocation::AllocationResponse>* PrepareAsyncAllocateRaw(::grpc::ClientContext* context, const ::allocation::AllocationRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Allocate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Allocate(::grpc::ServerContext* context, const ::allocation::AllocationRequest* request, ::allocation::AllocationResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Allocate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Allocate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Allocate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Allocate(::grpc::ServerContext* /*context*/, const ::allocation::AllocationRequest* /*request*/, ::allocation::AllocationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAllocate(::grpc::ServerContext* context, ::allocation::AllocationRequest* request, ::grpc::ServerAsyncResponseWriter< ::allocation::AllocationResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Allocate<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Allocate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Allocate() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::allocation::AllocationRequest, ::allocation::AllocationResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::allocation::AllocationRequest* request, ::allocation::AllocationResponse* response) { return this->Allocate(context, request, response); }));}
    void SetMessageAllocatorFor_Allocate(
        ::grpc::experimental::MessageAllocator< ::allocation::AllocationRequest, ::allocation::AllocationResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::allocation::AllocationRequest, ::allocation::AllocationResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Allocate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Allocate(::grpc::ServerContext* /*context*/, const ::allocation::AllocationRequest* /*request*/, ::allocation::AllocationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Allocate(
      ::grpc::CallbackServerContext* /*context*/, const ::allocation::AllocationRequest* /*request*/, ::allocation::AllocationResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Allocate(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::allocation::AllocationRequest* /*request*/, ::allocation::AllocationResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Allocate<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Allocate<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Allocate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Allocate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Allocate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Allocate(::grpc::ServerContext* /*context*/, const ::allocation::AllocationRequest* /*request*/, ::allocation::AllocationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Allocate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Allocate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Allocate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Allocate(::grpc::ServerContext* /*context*/, const ::allocation::AllocationRequest* /*request*/, ::allocation::AllocationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAllocate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Allocate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Allocate() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Allocate(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Allocate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Allocate(::grpc::ServerContext* /*context*/, const ::allocation::AllocationRequest* /*request*/, ::allocation::AllocationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Allocate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Allocate(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Allocate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Allocate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::allocation::AllocationRequest, ::allocation::AllocationResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::allocation::AllocationRequest, ::allocation::AllocationResponse>* streamer) {
                       return this->StreamedAllocate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Allocate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Allocate(::grpc::ServerContext* /*context*/, const ::allocation::AllocationRequest* /*request*/, ::allocation::AllocationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAllocate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::allocation::AllocationRequest,::allocation::AllocationResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Allocate<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Allocate<Service > StreamedService;
};

}  // namespace allocation


#endif  // GRPC_agones_2fallocation_2eproto__INCLUDED
