// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: runtime/healthcheck.proto

#include "runtime/healthcheck.pb.h"
#include "runtime/healthcheck.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace improbable {
namespace platform {
namespace runtime {

static const char* HealthCheckService_method_names[] = {
  "/improbable.platform.runtime.HealthCheckService/HealthCheck",
};

std::unique_ptr< HealthCheckService::Stub> HealthCheckService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HealthCheckService::Stub> stub(new HealthCheckService::Stub(channel));
  return stub;
}

HealthCheckService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_HealthCheck_(HealthCheckService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HealthCheckService::Stub::HealthCheck(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::improbable::platform::runtime::HealthCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_HealthCheck_, context, request, response);
}

void HealthCheckService::Stub::experimental_async::HealthCheck(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::improbable::platform::runtime::HealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, std::move(f));
}

void HealthCheckService::Stub::experimental_async::HealthCheck(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::improbable::platform::runtime::HealthCheckResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::HealthCheckResponse>* HealthCheckService::Stub::PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::improbable::platform::runtime::HealthCheckResponse>::Create(channel_.get(), cq, rpcmethod_HealthCheck_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::HealthCheckResponse>* HealthCheckService::Stub::AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHealthCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

HealthCheckService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HealthCheckService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HealthCheckService::Service, ::google::protobuf::Empty, ::improbable::platform::runtime::HealthCheckResponse>(
          [](HealthCheckService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::improbable::platform::runtime::HealthCheckResponse* resp) {
               return service->HealthCheck(ctx, req, resp);
             }, this)));
}

HealthCheckService::Service::~Service() {
}

::grpc::Status HealthCheckService::Service::HealthCheck(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::improbable::platform::runtime::HealthCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace improbable
}  // namespace platform
}  // namespace runtime

