// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: runtime/receptionist.proto

#include "runtime/receptionist.pb.h"
#include "runtime/receptionist.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace improbable {
namespace platform {
namespace runtime {

static const char* ReceptionistService_method_names[] = {
  "/improbable.platform.runtime.ReceptionistService/Login",
  "/improbable.platform.runtime.ReceptionistService/RemainingCapacity",
};

std::unique_ptr< ReceptionistService::Stub> ReceptionistService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ReceptionistService::Stub> stub(new ReceptionistService::Stub(channel));
  return stub;
}

ReceptionistService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Login_(ReceptionistService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RemainingCapacity_(ReceptionistService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ReceptionistService::Stub::Login(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest& request, ::improbable::platform::runtime::LoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Login_, context, request, response);
}

void ReceptionistService::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest* request, ::improbable::platform::runtime::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void ReceptionistService::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest* request, ::improbable::platform::runtime::LoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::LoginResponse>* ReceptionistService::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::improbable::platform::runtime::LoginResponse>::Create(channel_.get(), cq, rpcmethod_Login_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::LoginResponse>* ReceptionistService::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ReceptionistService::Stub::RemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest& request, ::improbable::platform::runtime::RemainingCapacityResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RemainingCapacity_, context, request, response);
}

void ReceptionistService::Stub::experimental_async::RemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest* request, ::improbable::platform::runtime::RemainingCapacityResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RemainingCapacity_, context, request, response, std::move(f));
}

void ReceptionistService::Stub::experimental_async::RemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest* request, ::improbable::platform::runtime::RemainingCapacityResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RemainingCapacity_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::RemainingCapacityResponse>* ReceptionistService::Stub::PrepareAsyncRemainingCapacityRaw(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::improbable::platform::runtime::RemainingCapacityResponse>::Create(channel_.get(), cq, rpcmethod_RemainingCapacity_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::RemainingCapacityResponse>* ReceptionistService::Stub::AsyncRemainingCapacityRaw(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRemainingCapacityRaw(context, request, cq);
  result->StartCall();
  return result;
}

ReceptionistService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ReceptionistService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ReceptionistService::Service, ::improbable::platform::runtime::LoginRequest, ::improbable::platform::runtime::LoginResponse>(
          [](ReceptionistService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::improbable::platform::runtime::LoginRequest* req,
             ::improbable::platform::runtime::LoginResponse* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ReceptionistService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ReceptionistService::Service, ::improbable::platform::runtime::RemainingCapacityRequest, ::improbable::platform::runtime::RemainingCapacityResponse>(
          [](ReceptionistService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::improbable::platform::runtime::RemainingCapacityRequest* req,
             ::improbable::platform::runtime::RemainingCapacityResponse* resp) {
               return service->RemainingCapacity(ctx, req, resp);
             }, this)));
}

ReceptionistService::Service::~Service() {
}

::grpc::Status ReceptionistService::Service::Login(::grpc::ServerContext* context, const ::improbable::platform::runtime::LoginRequest* request, ::improbable::platform::runtime::LoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ReceptionistService::Service::RemainingCapacity(::grpc::ServerContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest* request, ::improbable::platform::runtime::RemainingCapacityResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace improbable
}  // namespace platform
}  // namespace runtime

