// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: runtime/receptionist.proto
// Original file comments:
// Copyright (c) 2015 Improbable Worlds Ltd. All Rights Reserved.
#ifndef GRPC_runtime_2freceptionist_2eproto__INCLUDED
#define GRPC_runtime_2freceptionist_2eproto__INCLUDED

#include "runtime/receptionist.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace improbable {
namespace platform {
namespace runtime {

// ReceptionistService should only exist once on a deployment.
class ReceptionistService final {
 public:
  static constexpr char const* service_full_name() {
    return "improbable.platform.runtime.ReceptionistService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Login requests a deployment login from the receptionist.
    // The flow is as follows:
    // 1. The worker sends LoginRequest to receptionist, specifying protocol capabilities it can
    //    support.
    // 2. The receptionist replies with a LoginResponse, which contains the basic address and port
    //    to connect to a bridge and other settings that match the capabilities sent by the worker.
    virtual ::grpc::Status Login(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest& request, ::improbable::platform::runtime::LoginResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::improbable::platform::runtime::LoginResponse>> AsyncLogin(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::improbable::platform::runtime::LoginResponse>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::improbable::platform::runtime::LoginResponse>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::improbable::platform::runtime::LoginResponse>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    // RemainingCapacity the remaining capacity (number of additional players that can be connected) from the
    // receptionist.
    virtual ::grpc::Status RemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest& request, ::improbable::platform::runtime::RemainingCapacityResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::improbable::platform::runtime::RemainingCapacityResponse>> AsyncRemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::improbable::platform::runtime::RemainingCapacityResponse>>(AsyncRemainingCapacityRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::improbable::platform::runtime::RemainingCapacityResponse>> PrepareAsyncRemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::improbable::platform::runtime::RemainingCapacityResponse>>(PrepareAsyncRemainingCapacityRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Login requests a deployment login from the receptionist.
      // The flow is as follows:
      // 1. The worker sends LoginRequest to receptionist, specifying protocol capabilities it can
      //    support.
      // 2. The receptionist replies with a LoginResponse, which contains the basic address and port
      //    to connect to a bridge and other settings that match the capabilities sent by the worker.
      virtual void Login(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest* request, ::improbable::platform::runtime::LoginResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Login(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest* request, ::improbable::platform::runtime::LoginResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Login(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest* request, ::improbable::platform::runtime::LoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // RemainingCapacity the remaining capacity (number of additional players that can be connected) from the
      // receptionist.
      virtual void RemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest* request, ::improbable::platform::runtime::RemainingCapacityResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest* request, ::improbable::platform::runtime::RemainingCapacityResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest* request, ::improbable::platform::runtime::RemainingCapacityResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::improbable::platform::runtime::LoginResponse>* AsyncLoginRaw(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::improbable::platform::runtime::LoginResponse>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::improbable::platform::runtime::RemainingCapacityResponse>* AsyncRemainingCapacityRaw(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::improbable::platform::runtime::RemainingCapacityResponse>* PrepareAsyncRemainingCapacityRaw(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Login(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest& request, ::improbable::platform::runtime::LoginResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::LoginResponse>> AsyncLogin(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::LoginResponse>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::LoginResponse>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::LoginResponse>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    ::grpc::Status RemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest& request, ::improbable::platform::runtime::RemainingCapacityResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::RemainingCapacityResponse>> AsyncRemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::RemainingCapacityResponse>>(AsyncRemainingCapacityRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::RemainingCapacityResponse>> PrepareAsyncRemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::RemainingCapacityResponse>>(PrepareAsyncRemainingCapacityRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Login(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest* request, ::improbable::platform::runtime::LoginResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Login(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest* request, ::improbable::platform::runtime::LoginResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Login(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest* request, ::improbable::platform::runtime::LoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void RemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest* request, ::improbable::platform::runtime::RemainingCapacityResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest* request, ::improbable::platform::runtime::RemainingCapacityResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RemainingCapacity(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest* request, ::improbable::platform::runtime::RemainingCapacityResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::LoginResponse>* AsyncLoginRaw(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::LoginResponse>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::improbable::platform::runtime::LoginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::RemainingCapacityResponse>* AsyncRemainingCapacityRaw(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::improbable::platform::runtime::RemainingCapacityResponse>* PrepareAsyncRemainingCapacityRaw(::grpc::ClientContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Login_;
    const ::grpc::internal::RpcMethod rpcmethod_RemainingCapacity_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Login requests a deployment login from the receptionist.
    // The flow is as follows:
    // 1. The worker sends LoginRequest to receptionist, specifying protocol capabilities it can
    //    support.
    // 2. The receptionist replies with a LoginResponse, which contains the basic address and port
    //    to connect to a bridge and other settings that match the capabilities sent by the worker.
    virtual ::grpc::Status Login(::grpc::ServerContext* context, const ::improbable::platform::runtime::LoginRequest* request, ::improbable::platform::runtime::LoginResponse* response);
    // RemainingCapacity the remaining capacity (number of additional players that can be connected) from the
    // receptionist.
    virtual ::grpc::Status RemainingCapacity(::grpc::ServerContext* context, const ::improbable::platform::runtime::RemainingCapacityRequest* request, ::improbable::platform::runtime::RemainingCapacityResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Login() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::improbable::platform::runtime::LoginRequest* /*request*/, ::improbable::platform::runtime::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLogin(::grpc::ServerContext* context, ::improbable::platform::runtime::LoginRequest* request, ::grpc::ServerAsyncResponseWriter< ::improbable::platform::runtime::LoginResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RemainingCapacity : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RemainingCapacity() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RemainingCapacity() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemainingCapacity(::grpc::ServerContext* /*context*/, const ::improbable::platform::runtime::RemainingCapacityRequest* /*request*/, ::improbable::platform::runtime::RemainingCapacityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemainingCapacity(::grpc::ServerContext* context, ::improbable::platform::runtime::RemainingCapacityRequest* request, ::grpc::ServerAsyncResponseWriter< ::improbable::platform::runtime::RemainingCapacityResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Login<WithAsyncMethod_RemainingCapacity<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Login() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::improbable::platform::runtime::LoginRequest, ::improbable::platform::runtime::LoginResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::improbable::platform::runtime::LoginRequest* request, ::improbable::platform::runtime::LoginResponse* response) { return this->Login(context, request, response); }));}
    void SetMessageAllocatorFor_Login(
        ::grpc::experimental::MessageAllocator< ::improbable::platform::runtime::LoginRequest, ::improbable::platform::runtime::LoginResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::improbable::platform::runtime::LoginRequest, ::improbable::platform::runtime::LoginResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::improbable::platform::runtime::LoginRequest* /*request*/, ::improbable::platform::runtime::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Login(
      ::grpc::CallbackServerContext* /*context*/, const ::improbable::platform::runtime::LoginRequest* /*request*/, ::improbable::platform::runtime::LoginResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Login(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::improbable::platform::runtime::LoginRequest* /*request*/, ::improbable::platform::runtime::LoginResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RemainingCapacity : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_RemainingCapacity() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::improbable::platform::runtime::RemainingCapacityRequest, ::improbable::platform::runtime::RemainingCapacityResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::improbable::platform::runtime::RemainingCapacityRequest* request, ::improbable::platform::runtime::RemainingCapacityResponse* response) { return this->RemainingCapacity(context, request, response); }));}
    void SetMessageAllocatorFor_RemainingCapacity(
        ::grpc::experimental::MessageAllocator< ::improbable::platform::runtime::RemainingCapacityRequest, ::improbable::platform::runtime::RemainingCapacityResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::improbable::platform::runtime::RemainingCapacityRequest, ::improbable::platform::runtime::RemainingCapacityResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_RemainingCapacity() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemainingCapacity(::grpc::ServerContext* /*context*/, const ::improbable::platform::runtime::RemainingCapacityRequest* /*request*/, ::improbable::platform::runtime::RemainingCapacityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RemainingCapacity(
      ::grpc::CallbackServerContext* /*context*/, const ::improbable::platform::runtime::RemainingCapacityRequest* /*request*/, ::improbable::platform::runtime::RemainingCapacityResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RemainingCapacity(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::improbable::platform::runtime::RemainingCapacityRequest* /*request*/, ::improbable::platform::runtime::RemainingCapacityResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Login<ExperimentalWithCallbackMethod_RemainingCapacity<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Login<ExperimentalWithCallbackMethod_RemainingCapacity<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Login() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::improbable::platform::runtime::LoginRequest* /*request*/, ::improbable::platform::runtime::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RemainingCapacity : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RemainingCapacity() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RemainingCapacity() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemainingCapacity(::grpc::ServerContext* /*context*/, const ::improbable::platform::runtime::RemainingCapacityRequest* /*request*/, ::improbable::platform::runtime::RemainingCapacityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Login() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::improbable::platform::runtime::LoginRequest* /*request*/, ::improbable::platform::runtime::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLogin(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RemainingCapacity : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RemainingCapacity() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RemainingCapacity() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemainingCapacity(::grpc::ServerContext* /*context*/, const ::improbable::platform::runtime::RemainingCapacityRequest* /*request*/, ::improbable::platform::runtime::RemainingCapacityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemainingCapacity(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Login() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Login(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::improbable::platform::runtime::LoginRequest* /*request*/, ::improbable::platform::runtime::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Login(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Login(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RemainingCapacity : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_RemainingCapacity() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RemainingCapacity(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_RemainingCapacity() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemainingCapacity(::grpc::ServerContext* /*context*/, const ::improbable::platform::runtime::RemainingCapacityRequest* /*request*/, ::improbable::platform::runtime::RemainingCapacityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RemainingCapacity(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RemainingCapacity(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Login() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::improbable::platform::runtime::LoginRequest, ::improbable::platform::runtime::LoginResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::improbable::platform::runtime::LoginRequest, ::improbable::platform::runtime::LoginResponse>* streamer) {
                       return this->StreamedLogin(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::improbable::platform::runtime::LoginRequest* /*request*/, ::improbable::platform::runtime::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLogin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::improbable::platform::runtime::LoginRequest,::improbable::platform::runtime::LoginResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RemainingCapacity : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RemainingCapacity() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::improbable::platform::runtime::RemainingCapacityRequest, ::improbable::platform::runtime::RemainingCapacityResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::improbable::platform::runtime::RemainingCapacityRequest, ::improbable::platform::runtime::RemainingCapacityResponse>* streamer) {
                       return this->StreamedRemainingCapacity(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RemainingCapacity() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RemainingCapacity(::grpc::ServerContext* /*context*/, const ::improbable::platform::runtime::RemainingCapacityRequest* /*request*/, ::improbable::platform::runtime::RemainingCapacityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRemainingCapacity(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::improbable::platform::runtime::RemainingCapacityRequest,::improbable::platform::runtime::RemainingCapacityResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Login<WithStreamedUnaryMethod_RemainingCapacity<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Login<WithStreamedUnaryMethod_RemainingCapacity<Service > > StreamedService;
};

}  // namespace runtime
}  // namespace platform
}  // namespace improbable


#endif  // GRPC_runtime_2freceptionist_2eproto__INCLUDED
