// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runtime/worker_attribute.proto

#include "runtime/worker_attribute.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_runtime_2fworker_5fattribute_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_WorkerAttribute_runtime_2fworker_5fattribute_2eproto;
namespace improbable {
namespace platform {
namespace runtime {
class WorkerAttributeDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<WorkerAttribute> _instance;
} _WorkerAttribute_default_instance_;
class WorkerAttributeSetDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<WorkerAttributeSet> _instance;
} _WorkerAttributeSet_default_instance_;
}  // namespace runtime
}  // namespace platform
}  // namespace improbable
static void InitDefaultsscc_info_WorkerAttribute_runtime_2fworker_5fattribute_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::improbable::platform::runtime::_WorkerAttribute_default_instance_;
    new (ptr) ::improbable::platform::runtime::WorkerAttribute();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_WorkerAttribute_runtime_2fworker_5fattribute_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_WorkerAttribute_runtime_2fworker_5fattribute_2eproto}, {}};

static void InitDefaultsscc_info_WorkerAttributeSet_runtime_2fworker_5fattribute_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::improbable::platform::runtime::_WorkerAttributeSet_default_instance_;
    new (ptr) ::improbable::platform::runtime::WorkerAttributeSet();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_WorkerAttributeSet_runtime_2fworker_5fattribute_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_WorkerAttributeSet_runtime_2fworker_5fattribute_2eproto}, {
      &scc_info_WorkerAttribute_runtime_2fworker_5fattribute_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_runtime_2fworker_5fattribute_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_runtime_2fworker_5fattribute_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_runtime_2fworker_5fattribute_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_runtime_2fworker_5fattribute_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::improbable::platform::runtime::WorkerAttribute, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::improbable::platform::runtime::WorkerAttribute, name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::improbable::platform::runtime::WorkerAttributeSet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::improbable::platform::runtime::WorkerAttributeSet, attribute_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::improbable::platform::runtime::WorkerAttribute)},
  { 6, -1, sizeof(::improbable::platform::runtime::WorkerAttributeSet)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::improbable::platform::runtime::_WorkerAttribute_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::improbable::platform::runtime::_WorkerAttributeSet_default_instance_),
};

const char descriptor_table_protodef_runtime_2fworker_5fattribute_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036runtime/worker_attribute.proto\022\033improb"
  "able.platform.runtime\"\037\n\017WorkerAttribute"
  "\022\014\n\004name\030\001 \001(\t\"U\n\022WorkerAttributeSet\022\?\n\t"
  "attribute\030\001 \003(\0132,.improbable.platform.ru"
  "ntime.WorkerAttributeB\026B\024WorkerAttribute"
  "Protob\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_runtime_2fworker_5fattribute_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_runtime_2fworker_5fattribute_2eproto_sccs[2] = {
  &scc_info_WorkerAttribute_runtime_2fworker_5fattribute_2eproto.base,
  &scc_info_WorkerAttributeSet_runtime_2fworker_5fattribute_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_runtime_2fworker_5fattribute_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_runtime_2fworker_5fattribute_2eproto = {
  false, false, descriptor_table_protodef_runtime_2fworker_5fattribute_2eproto, "runtime/worker_attribute.proto", 213,
  &descriptor_table_runtime_2fworker_5fattribute_2eproto_once, descriptor_table_runtime_2fworker_5fattribute_2eproto_sccs, descriptor_table_runtime_2fworker_5fattribute_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_runtime_2fworker_5fattribute_2eproto::offsets,
  file_level_metadata_runtime_2fworker_5fattribute_2eproto, 2, file_level_enum_descriptors_runtime_2fworker_5fattribute_2eproto, file_level_service_descriptors_runtime_2fworker_5fattribute_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_runtime_2fworker_5fattribute_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_runtime_2fworker_5fattribute_2eproto)), true);
namespace improbable {
namespace platform {
namespace runtime {

// ===================================================================

class WorkerAttribute::_Internal {
 public:
};

WorkerAttribute::WorkerAttribute(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:improbable.platform.runtime.WorkerAttribute)
}
WorkerAttribute::WorkerAttribute(const WorkerAttribute& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:improbable.platform.runtime.WorkerAttribute)
}

void WorkerAttribute::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_WorkerAttribute_runtime_2fworker_5fattribute_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

WorkerAttribute::~WorkerAttribute() {
  // @@protoc_insertion_point(destructor:improbable.platform.runtime.WorkerAttribute)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void WorkerAttribute::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void WorkerAttribute::ArenaDtor(void* object) {
  WorkerAttribute* _this = reinterpret_cast< WorkerAttribute* >(object);
  (void)_this;
}
void WorkerAttribute::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void WorkerAttribute::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const WorkerAttribute& WorkerAttribute::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_WorkerAttribute_runtime_2fworker_5fattribute_2eproto.base);
  return *internal_default_instance();
}


void WorkerAttribute::Clear() {
// @@protoc_insertion_point(message_clear_start:improbable.platform.runtime.WorkerAttribute)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WorkerAttribute::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "improbable.platform.runtime.WorkerAttribute.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* WorkerAttribute::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:improbable.platform.runtime.WorkerAttribute)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "improbable.platform.runtime.WorkerAttribute.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:improbable.platform.runtime.WorkerAttribute)
  return target;
}

size_t WorkerAttribute::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:improbable.platform.runtime.WorkerAttribute)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WorkerAttribute::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:improbable.platform.runtime.WorkerAttribute)
  GOOGLE_DCHECK_NE(&from, this);
  const WorkerAttribute* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<WorkerAttribute>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:improbable.platform.runtime.WorkerAttribute)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:improbable.platform.runtime.WorkerAttribute)
    MergeFrom(*source);
  }
}

void WorkerAttribute::MergeFrom(const WorkerAttribute& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:improbable.platform.runtime.WorkerAttribute)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {
    _internal_set_name(from._internal_name());
  }
}

void WorkerAttribute::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:improbable.platform.runtime.WorkerAttribute)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WorkerAttribute::CopyFrom(const WorkerAttribute& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:improbable.platform.runtime.WorkerAttribute)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WorkerAttribute::IsInitialized() const {
  return true;
}

void WorkerAttribute::InternalSwap(WorkerAttribute* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata WorkerAttribute::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class WorkerAttributeSet::_Internal {
 public:
};

WorkerAttributeSet::WorkerAttributeSet(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  attribute_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:improbable.platform.runtime.WorkerAttributeSet)
}
WorkerAttributeSet::WorkerAttributeSet(const WorkerAttributeSet& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      attribute_(from.attribute_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:improbable.platform.runtime.WorkerAttributeSet)
}

void WorkerAttributeSet::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_WorkerAttributeSet_runtime_2fworker_5fattribute_2eproto.base);
}

WorkerAttributeSet::~WorkerAttributeSet() {
  // @@protoc_insertion_point(destructor:improbable.platform.runtime.WorkerAttributeSet)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void WorkerAttributeSet::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void WorkerAttributeSet::ArenaDtor(void* object) {
  WorkerAttributeSet* _this = reinterpret_cast< WorkerAttributeSet* >(object);
  (void)_this;
}
void WorkerAttributeSet::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void WorkerAttributeSet::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const WorkerAttributeSet& WorkerAttributeSet::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_WorkerAttributeSet_runtime_2fworker_5fattribute_2eproto.base);
  return *internal_default_instance();
}


void WorkerAttributeSet::Clear() {
// @@protoc_insertion_point(message_clear_start:improbable.platform.runtime.WorkerAttributeSet)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  attribute_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WorkerAttributeSet::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .improbable.platform.runtime.WorkerAttribute attribute = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_attribute(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* WorkerAttributeSet::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:improbable.platform.runtime.WorkerAttributeSet)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .improbable.platform.runtime.WorkerAttribute attribute = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_attribute_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_attribute(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:improbable.platform.runtime.WorkerAttributeSet)
  return target;
}

size_t WorkerAttributeSet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:improbable.platform.runtime.WorkerAttributeSet)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .improbable.platform.runtime.WorkerAttribute attribute = 1;
  total_size += 1UL * this->_internal_attribute_size();
  for (const auto& msg : this->attribute_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WorkerAttributeSet::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:improbable.platform.runtime.WorkerAttributeSet)
  GOOGLE_DCHECK_NE(&from, this);
  const WorkerAttributeSet* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<WorkerAttributeSet>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:improbable.platform.runtime.WorkerAttributeSet)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:improbable.platform.runtime.WorkerAttributeSet)
    MergeFrom(*source);
  }
}

void WorkerAttributeSet::MergeFrom(const WorkerAttributeSet& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:improbable.platform.runtime.WorkerAttributeSet)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  attribute_.MergeFrom(from.attribute_);
}

void WorkerAttributeSet::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:improbable.platform.runtime.WorkerAttributeSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WorkerAttributeSet::CopyFrom(const WorkerAttributeSet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:improbable.platform.runtime.WorkerAttributeSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WorkerAttributeSet::IsInitialized() const {
  return true;
}

void WorkerAttributeSet::InternalSwap(WorkerAttributeSet* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  attribute_.InternalSwap(&other->attribute_);
}

::PROTOBUF_NAMESPACE_ID::Metadata WorkerAttributeSet::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace runtime
}  // namespace platform
}  // namespace improbable
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::improbable::platform::runtime::WorkerAttribute* Arena::CreateMaybeMessage< ::improbable::platform::runtime::WorkerAttribute >(Arena* arena) {
  return Arena::CreateMessageInternal< ::improbable::platform::runtime::WorkerAttribute >(arena);
}
template<> PROTOBUF_NOINLINE ::improbable::platform::runtime::WorkerAttributeSet* Arena::CreateMaybeMessage< ::improbable::platform::runtime::WorkerAttributeSet >(Arena* arena) {
  return Arena::CreateMessageInternal< ::improbable::platform::runtime::WorkerAttributeSet >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
